### PR TITLE
Added Support for ShadowBringers Classes

### PR DESCRIPTION
**Pull request by JustOkayGames**
Gunbreaker and Dancer job icons uploaded.

Added bar color for Gunbreaker and Dancer.

Dark Knight bar color changed to a dark purple since Gunbreaker bar color is a dark blue.

### CODE REVIEW

**Comment by encadi** [comment]
Gunbreaker and scholar seem to have the same colour

**Comment by JustOkayGames** [comment]
@encadi I updated the color error for the jobs you mentioned and made some adjustment to all other job/class colors to help spread the color scheme. I made the Scholar job a light green to go along with the Summoner since they go hand to hand.

I attached the new updated rdmty.css file to fix these issues. Just replace the file in the ".../css" folder if you have downloaded the master locally.

Note: I've added color comments for the jobs in the .css file

[rdmty_classcolor_fix.zip](https://github.com/billyvg/OverlayPlugin-themes/files/3390470/rdmty_classcolor_fix.zip)

**Comment by encadi** [comment]
Thank you btw I tried to point it to the webpage in the url but it didnt seem to work so I just did a local url.

**Comment by JustOkayGames** [comment]
Yea unfortunately the webpage url no longer works but running locally works fine. I'm going to see if I can fix the end encounter button.

**Comment by billyvg** [comment]
Updated to use github pages so that the URL should work now: http://billyvg.github.io/OverlayPlugin-themes/rdmty_default

**Comment by encadi** [comment]
Scholar is back at being blue if you use the website link

**Pull request merged**
